### ISSUE TITLE
No (1)^3+(1)^3+(1)^3 = 3 output for k=3?

### ISSUE THREAD

**Issue by marconi1964** [AndrewVSutherland/SumsOfThreeCubes#2]
Thanks for open sourcing SumsOfThreeCubes. I tried it with k=3, but no solution output. Is it under expectation?

```
marconi:~/SumsOfThreeCubes$ ./zcubes 8 3 1 1e9 1e9 1e10
START:2022-06-11-05-47-02:n=8:k=3:pmin=2:pmax=1000000000:dmax=1000000000:zmax=10000000000:ver=1.1
END:2022-06-11-05-47-08:n=8:k=3:pmin=2:pmax=1000000000:dmax=1000000000:zmax=10000000000:sMB=199.3:pMB=0.0:rMB=204.3:secs=6.3:ver=1.1

```
It works with k=6 properly.

```
marconi:~/SumsOfThreeCubes$ ./zcubes 8 6 1 1e9 1e9 1e10
START:2022-06-11-05-58-18:n=8:k=6:pmin=2:pmax=1000000000:dmax=1000000000:zmax=10000000000:ver=1.1
SOLUTION:2022-06-11-05-58-19:k=6:d=7:Z=-43:*** (65)^3 + (-58)^3 + (-43)^3 = 6 ***
SOLUTION:2022-06-11-05-58-19:k=6:d=7:Z=-205:*** (644)^3 + (-637)^3 + (-205)^3 = 6 ***
SOLUTION:2022-06-11-05-58-19:k=6:d=107:Z=10529:*** (-60355)^3 + (60248)^3 + (10529)^3 = 6 ***
SOLUTION:2022-06-11-05-58-21:k=6:d=152522:Z=1426148:*** (-2593669)^3 + (2441147)^3 + (1426148)^3 = 6 ***
END:2022-06-11-05-58-26:n=8:k=6:pmin=2:pmax=1000000000:dmax=1000000000:zmax=10000000000:sMB=196.9:pMB=0.0:rMB=201.4:secs=8.8:ver=1.1

```

**Comment by AndrewVSutherland** [comment]
As explained in the introduction to our [article](https://www.pnas.org/doi/10.1073/pnas.2022377118), our algorithm only searches for solutions with |x| > |y| > |z|, because it is easy to find all solutions where two or more of |x|, |y|, |z| coincide using other methods.  One can solve the problem k=x^3+2y^3 using algorithms for solving Thue equations that are available in most computer algebra systems.  To do this for k=3 in PARI/GP you can just type `thue(thueinit(x^3+2),3)`, which will give the output `[[-5,4], [1,1]]` corresponding to the two solutions for k=3 with |x|,|y|,|z| not distinct.  You can try this yourself by pasting the code snippet above into the online [PARI/GP calculator](https://pari.math.u-bordeaux.fr/gp.html)

I should also note that our implementation does not check for solutions with d=1 because it iterates over d divisible by a prime p in the interval [pmin,pmax].  This means it will miss the solution (-11)^3+10^3+7^3 for k=12, for example. But for any particular value of k and d one can find all solutions by searching for integral points on an elliptic curve, as discussed in the last paragraph of section 3 of the paper, and for small k and d=1 this is very efficient.  This method has already been used to find all solutions with d=1 for k <= 1000 (there are none for any of the outstanding k).

**Comment by AndrewVSutherland** [comment]
I updated [README.md](https://github.com/AndrewVSutherland/SumsOfThreeCubes/blob/main/README.md) to clarify the restrictions on the solutions the algorithm will find.
